# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
encoding : UTF-8
timezone: Asia/Shanghai

permalink: /:categories/:title.html
# /:categories/:year/:month/:day/:title.html

title: XTopic学习分享 人人为我-我为人人
email: obullxl@126.com
description: Java编程,Spring Struts Webwork框架深入,XMLHTTP Ajax开发,Java Web开发,Java企业应用,Java设计模式,Java开源框架,Java应用服务器,Rich Client讨论,Ruby编程,Ruby DSL开发,Ruby on rails实践,JavaScript编程,敏捷软件开发XP TDD,软件配置管理,软件测试,项目管理UML,数据库
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xtopic.github.io"
#relative_permalinks: true

#twitter_username: jekyllrb
github_username:  xtopic

# Build settings
markdown: kramdown




